site_name: Kano Docs

repo_url: https://github.com/egliette/kano
repo_name: egliette/kano

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/logo.png
  palette:
    primary: pink
  features:
    - content.code.copy
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.footer
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.sections

nav:
  - Home:
    - index.md
    - Common utilities:
        - common/index.md
        - Image: common/image_utils.md

  - Common:
    - common/index.md
    - Image: common/image_utils.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
